[package]
name = "julia_set"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.24.5"
js-sys = "0.3.61"
num = "0.4.0"
wasm-bindgen = "0.2.84"
